### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by jccr** [atom-minimap/minimap-highlight-selected#13]
When I'm typing in a source file that's about 2000 lines long and I hold my backspace key to continuously remove some characters the editor freezes for a couple of seconds and begins to lag. Sometimes I encounter this freeze while typing as well.

I have isolated the performance problem down to this line:
https://github.com/atom-minimap/minimap-highlight-selected/blob/master/lib/minimap-highlight-selected-view.coffee#L93

I tested this with no packages enabled except for the core packages, this one, minimap and highlight-selected.

It seems that no matter what textbuffer transaction I do (move around the caret, type some text, delete some text) the onDidChangeSelectionRange event gets triggered by atom. Maybe this is an atom bug?

**Comment by abe33** [comment]
Thanks for the report, I think atom is right when it triggers `onDidChangeSelectionRange` on cursors moves, a cursor always have an associated selection, and the inverse is true as well. 
The thing is that when you move the cursor you just have an empty selection which is catched [here](https://github.com/atom-minimap/minimap-highlight-selected/blob/master/lib/minimap-highlight-selected-view.coffee#L42) so it shouldn't spend much time in the function if you just move the cursor.
I'll try to find some way to improve performances, suggestions are welcome.

**Comment by JCCR** [comment]
Ah you are right, I didn't notice that check.
Since I'm experiencing the slow down, I'll dig deeper and see what's actually going on on my end.

**Comment by quintanar401** [comment]
I also experience this delay but it is quite constant - if I press backspace to delete the last letter or digit before a non-letter in a large file (delete 'a' here for example: 'some line.a' ) my editor freezes for about a half of a second. This doesn't happen if I delete a special symbol, bracket and etc or type symbols or delete a non-last letter. Profiling shows that the source of the problem is here - MinimapHighlightSelectedView.prototype.handleSelection
