### ISSUE TITLE
Runs on Windows but not on linux

### ISSUE THREAD

**Issue by davidmoret** [atom-minimap/minimap-highlight-selected#6]
Hello,
I installed the package on linux and it doesn't work. I just sync my config via "sync-settings" on a windows machine and it works. I don't understand. 
Need specific information?

**Comment by abe33** [comment]
Yes, if possible: 

The Atom version you're running on both platforms, the minimap and plugin version, and the `highlight-selected` version. Also, on linux, is there any error message in the console?

**Comment by davidmoret** [comment]
Platform with which I have no problem :
Atom Version: 0.187.0
System : Windows 7
highlight-selected, v0.9.1
minimap, v4.6.0
minimap-highlight-selected, v4.2.0

Platform with which the package doesn't work : 
Atom Version: 0.177.0
System: linux 3.13.0-46-generic
highlight-selected, v0.9.1
minimap, v4.3.1
I don't have my linux for now but I remembered all packages were updated last night, so the minimap-highlight-selected version should be the last. I will look tonight if something appears in the console.

**Comment by abe33** [comment]
Looks like an issue with your Atom/minimap version on Linux, minimap-highlight-selected v4.2.0 is compatible with minimap >= v4.5 which itself is compatible only with atom >= 0.184.

Sorry for the inconvenience, I omitted to update the engine version of the minimap plugins, so there's updates that appears as available when they shouldn't be. My advice is to update Atom on your linux computer so that you can get all the recent updates. If you can't update Atom, you can try to downgrade the plugin using `apm install minimap-highlight-selected@4.1.0`.

**Comment by davidmoret** [comment]
I'll try that tonight. thank you

**Comment by fundon** [comment]
Closed.
If you need, reopen it. Thanks.
